### ISSUE TITLE
citing

### ISSUE THREAD

**Issue by hfmahmoud** [tseemann/snp-dists#12]
how do I cite snp-dists in a publication

**Comment by tseemann** [comment]
Until we publish it, just use the URL:  `https://github.com/tseemann/snp-dists`

**Comment by mbhall88** [comment]
Do you think you'll publish this still Torsten? Such a shame to not be able to "properly" give you credit for this great tool. Maybe even a Zenodo DOI could at least give you some just credit?

**Comment by mbhall88** [comment]
I also found a Zenodo entry at https://zenodo.org/record/1411986 for anyone coming across this.
