### ISSUE TITLE
Does snp-dists 0.2 count the number of Ns in an alignment too? Or does it ignore them?

### ISSUE THREAD

**Issue by slvrshot** [tseemann/snp-dists#18]
Question is basically the title.
I have an output file from Gubbins were recombinant regions in the core genome have been removed. These recombinant blocks appear as Ns in the alignment. 

Please help.

**Comment by tseemann** [comment]
It doesn't care what letters you have in your alignment.  If they are different, it counts. 
It was designed for true core SNP alignments only.
Future versions (some in github currently) will address this.
You may want to look at `disty` instead: https://github.com/c2-d2/disty
