### ISSUE TITLE
Segmentaion fault error on snp-dists v0.4

### ISSUE THREAD

**Issue by sseby** [tseemann/snp-dists#19]
Hi,
I am using the fasta alignment from from Gubbins as input to snp-dist. I would like to exclude Ns and include only ATCGs in the calculation. I see that snp-dists v0.4 has an option to do this, but this version fails giving segmentation fault error. Appreciate if you could please give some guidance on how to solve this issue ? snp-dists v0.2 works fine, but I do not want to use that since it doesn't have the option to exclude Ns.

Thanks,
Sandra

**Comment by andersgs** [comment]
Hi @sseby:

Edit the following line in `snpdists.h`:

`#define MAX_SEQ 1000000`

Make that value 1000.

Recompile, and try again.

Best. Anders.

**Comment by tseemann** [comment]
I currently only support official releases on snp-dists.

https://github.com/tseemann/snp-dists/releases

The current version is 0.2

**Comment by tseemann** [comment]
This was fixed in #9
