### ISSUE TITLE
LD_LIBRARY_PATH not needed?

### ISSUE THREAD

**Issue by tseemann** [tseemann/snp-dists#2]
```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

Is this needed @andrewjpage ?

I seem to get a static executable with my build.

**Comment by andrewjpage** [comment]
That was just what I had to do on my docker container to quickly get it working. If it can be removed, great

**Comment by tseemann** [comment]
LD_LIB_PATH is frowned upon. The correct way is to modify the binary itself using `patchelf --set-rpath`. This is being used in Brew a lot, to ensure binaries use brew dynlibs.

Example: https://raw.githubusercontent.com/tseemann/homebrew-science/86076ba8a2d0ba4fad0837f3c570e705632a0000/trf.rb
