### ISSUE TITLE
Duplicate sequences show a SNP difference of 1

### ISSUE THREAD

**Issue by ramadatta** [tseemann/snp-dists#21]
Hi Seemann,

I have run gubbins with two exact same sequences and fed the "polymorphic_sites.fasta" to snp-dists program. I expect no SNP difference between these two sequences since they are exactly same sequences. But I keep on getting 1 SNP difference. Is it a bug or Am I missing something here. 

Thanks.

My output looks like this:

```
$ snp-dists -b -c test.fasta

This is snp-dists 0.6
Read 2 sequences of length 100566
,Reference_CP028169.fasta.ref,CP028169_Duplicate.fasta
Reference_CP028169.fasta.ref,0,1
CP028169_Duplicate.fasta,1,0
```

**Comment by tseemann** [comment]
Did the file originate from a Mac or Windows computer?
it could be wrong "newline" endings.
What OS are you on?
If on Mac or LInux, run `dos2unix polymorphic_sites.fasta` and `mac2unix polymorphic_sites.fasta` on them and see if it fixes it?

**Comment by tseemann** [comment]
I tried the other direction `unix2dos` and it didn't cause any problems.

```
cat foo.fa && snp-dists -b -c foo.fa
>S1
ATGC
ATGC
>S2
ATGC
ATGC

This is snp-dists 0.6
Read 2 sequences of length 8
,S1,S2
S1,0,0
S2,0,0
```

**Comment by ramadatta** [comment]
Hi Seemann,

Thank you. I have generate the file in Linux only and could not trace the problem. Newlines seems to be correctly placed and may not be cause for this error. 

Please find the file for your reference. Thanks so much!

[test.fasta.zip](https://github.com/tseemann/snp-dists/files/2074562/test.fasta.zip)

**Comment by tseemann** [comment]
Your sequences are not the same (but they are the same length).
I put each sequence into a file called `1` and `2`
Here is the *first* difference:

```
% cmp 1 2
1 2 differ: byte 8100, line 1
$ cut -c 8099-8101 1
GNN
$ cut -c 8099-8101 2
GGC
```
There are many more.  They don't have the same distribution of letters:

```
Reference_CP028169.fasta.ref    dna     100566  |N    118  0.1% |A  22048 21.9% |T  22381 22.3% |G  27497 27.3%     |C  28361 28.2%
CP028169_Duplicate.fasta        dna     100566  |N     72  0.1% |A  22063 21.9% |T  22383 22.3% |G  27518 27.4%     |C  28369 28.2%
```
