### ISSUE TITLE
snpdists input?

### ISSUE THREAD

**Issue by foamy1881** [tseemann/snp-dists#35]
Can anyone advice me how to generate multiple alignment fasta from raw fastq? I have 400+ isolates and trying to generate a SNP distance matrix (none mash) to check for epidemiological link. i.e SNP coverage distance less than 12 SNPs between isolates and plot into a tree.. can anyone point me to a correct info? newbie in bioinformatics and as usual most of the time supervisor is not free all the time. I ended have to find info from the web and learn it that way. Any help will be greatly appreciated.

**Comment by tseemann** [comment]
Answer: Use `snippy-multi` from `snippy` package. This is also done by `nullarbor`.

Googling information on the web and reading SeqAnswers, Biostars, and github is how most bioinformticians learn their craft. Our field is always changing, so it is a key, and necessary skill.

SNP "thresholds" are risky and will be different for different organisms. eg. M.tb vs E.coli
